import type { Permission, Role } from "@/src/auth/access-control";

export type AppShell = "public" | "patient" | "psychologist" | "ops";

export type AppRoute = {
  path: string;
  component: string;
  shell: AppShell;
  allowGuests: boolean;
  allowedRoles: Role[];
  requiredPermissions: Permission[];
  navLabel?: string;
  navGroup?: "main" | "care" | "management" | "admin" | "account";
};

export const APP_ROUTES: AppRoute[] = [
  // Public marketing
  {
    path: "/",
    component: "Homepage",
    shell: "public",
    allowGuests: true,
    allowedRoles: ["guest", "patient", "psychologist", "practice_manager", "admin"],
    requiredPermissions: ["marketing.read"],
    navLabel: "Home",
    navGroup: "main",
  },
  {
    path: "/about",
    component: "AboutPage",
    shell: "public",
    allowGuests: true,
    allowedRoles: ["guest", "patient", "psychologist", "practice_manager", "admin"],
    requiredPermissions: ["marketing.read"],
    navLabel: "About",
    navGroup: "main",
  },
  {
    path: "/services",
    component: "ServicesPage",
    shell: "public",
    allowGuests: true,
    allowedRoles: ["guest", "patient", "psychologist", "practice_manager", "admin"],
    requiredPermissions: ["marketing.read"],
    navLabel: "Services",
    navGroup: "main",
  },
  {
    path: "/why-clink",
    component: "WhyClinkPage",
    shell: "public",
    allowGuests: true,
    allowedRoles: ["guest", "patient", "psychologist", "practice_manager", "admin"],
    requiredPermissions: ["marketing.read"],
    navLabel: "Why Tailored Psychology",
    navGroup: "main",
  },
  {
    path: "/pricing",
    component: "PricingPage",
    shell: "public",
    allowGuests: true,
    allowedRoles: ["guest", "patient", "psychologist", "practice_manager", "admin"],
    requiredPermissions: ["marketing.read"],
    navLabel: "Pricing",
    navGroup: "main",
  },
  {
    path: "/trust",
    component: "TrustPage",
    shell: "public",
    allowGuests: true,
    allowedRoles: ["guest", "patient", "psychologist", "practice_manager", "admin"],
    requiredPermissions: ["marketing.read"],
    navLabel: "Trust",
    navGroup: "main",
  },
  {
    path: "/privacy-policy",
    component: "PrivacyPolicyPage",
    shell: "public",
    allowGuests: true,
    allowedRoles: ["guest", "patient", "psychologist", "practice_manager", "admin"],
    requiredPermissions: ["marketing.read"],
  },
  {
    path: "/terms-of-service",
    component: "TermsOfServicePage",
    shell: "public",
    allowGuests: true,
    allowedRoles: ["guest", "patient", "psychologist", "practice_manager", "admin"],
    requiredPermissions: ["marketing.read"],
  },
  {
    path: "/conditions",
    component: "ConditionsIndexPage",
    shell: "public",
    allowGuests: true,
    allowedRoles: ["guest", "patient", "psychologist", "practice_manager", "admin"],
    requiredPermissions: ["marketing.read"],
    navLabel: "Conditions",
    navGroup: "main",
  },
  {
    path: "/conditions/:slug",
    component: "ConditionPage",
    shell: "public",
    allowGuests: true,
    allowedRoles: ["guest", "patient", "psychologist", "practice_manager", "admin"],
    requiredPermissions: ["marketing.read"],
  },
  // Auth routes
  {
    path: "/login",
    component: "LoginPage",
    shell: "public",
    allowGuests: true,
    allowedRoles: ["guest"],
    requiredPermissions: ["auth.guest-only"],
  },
  {
    path: "/register",
    component: "RegisterPage",
    shell: "public",
    allowGuests: true,
    allowedRoles: ["guest"],
    requiredPermissions: ["auth.guest-only"],
  },
  // Patient
  {
    path: "/patient/dashboard",
    component: "PatientDashboardPage",
    shell: "patient",
    allowGuests: false,
    allowedRoles: ["patient"],
    requiredPermissions: ["patient.portal.read"],
    navLabel: "Dashboard",
    navGroup: "main",
  },
  {
    path: "/patient/appointments",
    component: "PatientAppointmentsPage",
    shell: "patient",
    allowGuests: false,
    allowedRoles: ["patient"],
    requiredPermissions: ["patient.portal.read"],
    navLabel: "Appointments",
    navGroup: "care",
  },
  {
    path: "/patient/my-clinician",
    component: "PatientMyClinicianPage",
    shell: "patient",
    allowGuests: false,
    allowedRoles: ["patient"],
    requiredPermissions: ["patient.portal.read"],
    navLabel: "My clinician",
    navGroup: "care",
  },
  {
    path: "/patient/data-requests",
    component: "PatientDataRequestsPage",
    shell: "patient",
    allowGuests: false,
    allowedRoles: ["patient"],
    requiredPermissions: ["patient.portal.read"],
    navLabel: "Privacy Requests",
    navGroup: "account",
  },
  {
    path: "/patient/recordings",
    component: "PatientRecordingsPage",
    shell: "patient",
    allowGuests: false,
    allowedRoles: ["patient"],
    requiredPermissions: ["recordings.read"],
    navLabel: "Recordings",
    navGroup: "care",
  },
  {
    path: "/patient/book-appointment",
    component: "PatientBookAppointmentPage",
    shell: "patient",
    allowGuests: false,
    allowedRoles: ["patient"],
    requiredPermissions: ["patient.booking.create"],
    navLabel: "Book Appointment",
    navGroup: "care",
  },
  {
    path: "/patient/video-setup",
    component: "PatientVideoSetupPage",
    shell: "patient",
    allowGuests: false,
    allowedRoles: ["patient"],
    requiredPermissions: ["patient.portal.read"],
  },
  // Psychologist
  {
    path: "/psychologist/dashboard",
    component: "PsychologistDashboardPage",
    shell: "psychologist",
    allowGuests: false,
    allowedRoles: ["psychologist"],
    requiredPermissions: ["psychologist.portal.read"],
    navLabel: "Dashboard",
    navGroup: "main",
  },
  {
    path: "/psychologist/patients",
    component: "PsychologistPatientsPage",
    shell: "psychologist",
    allowGuests: false,
    allowedRoles: ["psychologist"],
    requiredPermissions: ["psychologist.portal.read"],
    navLabel: "Patients",
    navGroup: "care",
  },
  {
    path: "/psychologist/patients/:patientId",
    component: "PsychologistPatientProfilePage",
    shell: "psychologist",
    allowGuests: false,
    allowedRoles: ["psychologist"],
    requiredPermissions: ["psychologist.portal.read"],
  },
  {
    path: "/psychologist/notes",
    component: "PsychologistNotesPage",
    shell: "psychologist",
    allowGuests: false,
    allowedRoles: ["psychologist"],
    requiredPermissions: ["psychologist.portal.read"],
    navLabel: "Notes",
    navGroup: "care",
  },
  {
    path: "/psychologist/profile",
    component: "PsychologistProfilePage",
    shell: "psychologist",
    allowGuests: false,
    allowedRoles: ["psychologist"],
    requiredPermissions: ["psychologist.portal.read"],
    navLabel: "Profile",
    navGroup: "care",
  },
  {
    path: "/psychologist/schedule",
    component: "PsychologistSchedulePage",
    shell: "psychologist",
    allowGuests: false,
    allowedRoles: ["psychologist"],
    requiredPermissions: ["psychologist.portal.read"],
    navLabel: "Schedule",
    navGroup: "care",
  },
  {
    path: "/psychologist/recordings",
    component: "PsychologistRecordingsPage",
    shell: "psychologist",
    allowGuests: false,
    allowedRoles: ["psychologist"],
    requiredPermissions: ["recordings.read"],
    navLabel: "Recordings",
    navGroup: "care",
  },
  // Practice manager and admin shared ops
  {
    path: "/manager/dashboard",
    component: "PracticeManagerDashboardPage",
    shell: "ops",
    allowGuests: false,
    allowedRoles: ["practice_manager", "admin"],
    requiredPermissions: ["manager.portal.read"],
    navLabel: "Dashboard",
    navGroup: "management",
  },
  {
    path: "/manager/resources",
    component: "ManagerResourcesPage",
    shell: "ops",
    allowGuests: false,
    allowedRoles: ["psychologist", "practice_manager", "admin"],
    requiredPermissions: ["resources.manage"],
    navLabel: "Resources",
    navGroup: "management",
  },
  {
    path: "/manager/referrals",
    component: "ManagerReferralsPage",
    shell: "ops",
    allowGuests: false,
    allowedRoles: ["practice_manager", "admin"],
    requiredPermissions: ["referrals.verify"],
    navLabel: "Referrals",
    navGroup: "management",
  },
  {
    path: "/manager/privacy-requests",
    component: "ManagerPrivacyRequestsPage",
    shell: "ops",
    allowGuests: false,
    allowedRoles: ["practice_manager", "admin"],
    requiredPermissions: ["privacy.requests.manage"],
    navLabel: "Privacy Requests",
    navGroup: "management",
  },
  // Admin
  {
    path: "/admin/dashboard",
    component: "AdminDashboardPage",
    shell: "ops",
    allowGuests: false,
    allowedRoles: ["admin"],
    requiredPermissions: ["admin.portal.read"],
    navLabel: "Admin Dashboard",
    navGroup: "admin",
  },
  {
    path: "/admin/security-incidents",
    component: "AdminSecurityIncidentsPage",
    shell: "ops",
    allowGuests: false,
    allowedRoles: ["admin"],
    requiredPermissions: ["admin.portal.read"],
    navLabel: "Security Incidents",
    navGroup: "admin",
  },
  {
    path: "/admin/data-deletion",
    component: "AdminDataDeletionPage",
    shell: "ops",
    allowGuests: false,
    allowedRoles: ["practice_manager", "admin"],
    requiredPermissions: ["privacy.requests.manage"],
    navLabel: "Data Deletion",
    navGroup: "admin",
  },
  {
    path: "/admin/privacy-requests",
    component: "AdminPrivacyRequestsPage",
    shell: "ops",
    allowGuests: false,
    allowedRoles: ["practice_manager", "admin"],
    requiredPermissions: ["privacy.requests.manage"],
    navLabel: "Privacy Requests",
    navGroup: "admin",
  },
  {
    path: "/admin/referrals",
    component: "AdminReferralsPage",
    shell: "ops",
    allowGuests: false,
    allowedRoles: ["practice_manager", "admin"],
    requiredPermissions: ["referrals.verify"],
    navLabel: "Referrals",
    navGroup: "admin",
  },
  // Shared clinical routes
  {
    path: "/recordings",
    component: "RecordingsPage",
    shell: "ops",
    allowGuests: false,
    allowedRoles: ["patient", "psychologist", "practice_manager", "admin"],
    requiredPermissions: ["recordings.read"],
    navLabel: "Recordings",
    navGroup: "care",
  },
  {
    path: "/video-session/:appointmentId",
    component: "VideoCallPage",
    shell: "ops",
    allowGuests: false,
    allowedRoles: ["patient", "psychologist", "practice_manager", "admin"],
    requiredPermissions: ["video-session.join"],
  },
  {
    path: "/notification/:notificationId",
    component: "NotificationDetailPage",
    shell: "ops",
    allowGuests: false,
    allowedRoles: ["patient", "psychologist", "practice_manager", "admin"],
    requiredPermissions: ["video-session.join"],
  },
];
