import type { TutorialStepDef } from "@/src/tutorials/types"

export const PATIENT_WELCOME_STREAM_ID = "patient.welcome" as const

/** Completion is recorded when the user reaches this step (or finishes after it). */
export const PATIENT_WELCOME_LAST_STEP_ID = "patient.welcome.done" as const

/**
 * Patient portal orientation — PHI-free copy (Wave 16 §6.6).
 * Mixes shell targets, page wrappers (`patient.page.*`), and `pushPathOnNext` / `waitForRoute`
 * so the tour follows the real sidebar tabs and main content.
 */
export const patientWelcomeSteps: TutorialStepDef[] = [
  {
    id: "patient.welcome.sidebar",
    target: "shell.sidebar",
    title: "Your patient portal",
    body: "This sidebar is home base. Use it to open Dashboard, Appointments, your clinician, Billing, Resources, privacy requests, and Account. The footer has Book New Appointment and Logout. We keep the menu expanded during the tour—collapse it anytime with the rows icon.",
    side: "right",
    align: "start",
    waitForRoutes: ["/patient/dashboard", "/patient/onboarding"],
  },
  {
    id: "patient.welcome.search",
    target: "shell.header.search",
    title: "Search (wide screens)",
    body: "On larger screens you can search appointments and resources from here. On small screens it may be hidden so the header stays simple.",
    side: "bottom",
    align: "start",
    waitForRoutes: ["/patient/dashboard", "/patient/onboarding"],
  },
  {
    id: "patient.welcome.onboarding_area",
    target: "patient.page.onboarding",
    title: "Get set for care",
    body: "If you see this checklist, work through profile, booking intake, and notifications. Progress saves as you go—use Refresh on the checklist when you’re done with intake.",
    side: "left",
    align: "start",
    waitForRoute: "/patient/onboarding",
  },
  {
    id: "patient.welcome.dashboard_nav",
    target: "shell.sidebar.dashboard",
    title: "Dashboard tab",
    body: "Tap Next to open the Dashboard (or choose Dashboard here). That’s where reminders, upcoming visits, and quick shortcuts usually live.",
    side: "right",
    align: "start",
    waitForRoutes: ["/patient/dashboard", "/patient/onboarding"],
    pushPathOnNext: "/patient/dashboard",
  },
  {
    id: "patient.welcome.dashboard_page",
    target: "patient.page.dashboard",
    title: "Dashboard page",
    body: "This area updates per page while the shell stays the same. On the dashboard you’ll see greeting text, cards for the next session, mood check-in, journey timeline, and more as your care progresses.",
    side: "left",
    align: "start",
    waitForRoute: "/patient/dashboard",
  },
  {
    id: "patient.welcome.quick_actions",
    target: "patient.dashboard.quick-actions",
    title: "Quick actions",
    body: "These shortcuts jump to common tasks—book a visit, open chat when a session window exists, or jump to billing—without hunting through menus.",
    side: "left",
    align: "start",
    waitForRoute: "/patient/dashboard",
  },
  {
    id: "patient.welcome.appointments_nav",
    target: "shell.sidebar.appointments",
    title: "Appointments tab",
    body: "Next opens the Appointments page. That’s where upcoming and past visits are listed, with status and timing in one place.",
    side: "right",
    align: "start",
    waitForRoute: "/patient/dashboard",
    pushPathOnNext: "/patient/appointments",
  },
  {
    id: "patient.welcome.appointments_page",
    target: "patient.page.appointments",
    title: "Appointments page",
    body: "Review what’s scheduled, follow status labels, and use clinic actions from this view. Booking confirmations also surface in notifications.",
    side: "left",
    align: "start",
    waitForRoute: "/patient/appointments",
  },
  {
    id: "patient.welcome.clinician_nav",
    target: "shell.sidebar.my-clinician",
    title: "My clinician",
    body: "Open the clinician area to see who is linked to your care from live appointments, professional context, and session-related details—without mixing in other portals.",
    side: "right",
    align: "start",
    waitForRoute: "/patient/appointments",
    pushPathOnNext: "/patient/my-clinician",
  },
  {
    id: "patient.welcome.clinician_page",
    target: "patient.page.my-clinician",
    title: "My clinician page",
    body: "Cards here reflect your care team. When no clinician is linked yet, you’ll see an empty state until visits connect you to a provider.",
    side: "left",
    align: "start",
    waitForRoute: "/patient/my-clinician",
  },
  {
    id: "patient.welcome.billing_nav",
    target: "shell.sidebar.billing",
    title: "Billing",
    body: "Next opens Billing (invoices). Download PDFs or text exports when available and track issued dates and status from one list.",
    side: "right",
    align: "start",
    waitForRoute: "/patient/my-clinician",
    pushPathOnNext: "/patient/invoices",
  },
  {
    id: "patient.welcome.invoices_page",
    target: "patient.page.invoices",
    title: "Invoices & billing",
    body: "Invoice rows show identifiers, dates, amounts, and status. Use download when you need a copy for records or rebates.",
    side: "left",
    align: "start",
    waitForRoute: "/patient/invoices",
  },
  {
    id: "patient.welcome.resources_nav",
    target: "shell.sidebar.resources",
    title: "Resources",
    body: "Resources gathers education and reading materials your clinic surfaces in the portal—organized by category.",
    side: "right",
    align: "start",
    waitForRoute: "/patient/invoices",
    pushPathOnNext: "/patient/resources",
  },
  {
    id: "patient.welcome.resources_page",
    target: "patient.page.resources",
    title: "Resources page",
    body: "Browse category cards for overviews. This is general information—not a substitute for session advice from your clinician.",
    side: "left",
    align: "start",
    waitForRoute: "/patient/resources",
  },
  {
    id: "patient.welcome.privacy_nav",
    target: "shell.sidebar.privacy-requests",
    title: "Privacy requests",
    body: "Submit access or correction requests and track status and due dates. Use clear details so governance can process them quickly.",
    side: "right",
    align: "start",
    waitForRoute: "/patient/resources",
    pushPathOnNext: "/patient/data-requests",
  },
  {
    id: "patient.welcome.privacy_page",
    target: "patient.page.privacy-requests",
    title: "Data requests page",
    body: "Start a new request from the buttons, then monitor the list below for updates. Sensitive flows stay in this dedicated area.",
    side: "left",
    align: "start",
    waitForRoute: "/patient/data-requests",
  },
  {
    id: "patient.welcome.account_nav",
    target: "shell.sidebar.account",
    title: "Account",
    body: "Account holds profile edits, password, notification preferences, and data export tools—everything about your login and how we reach you.",
    side: "right",
    align: "start",
    waitForRoute: "/patient/data-requests",
    pushPathOnNext: "/patient/account",
  },
  {
    id: "patient.welcome.account_page",
    target: "patient.page.account",
    title: "Account & security",
    body: "Expand Profile, Password, or Notifications from the cards. Data export requests run here too—watch status messages after you request a package.",
    side: "left",
    align: "start",
    waitForRoute: "/patient/account",
  },
  {
    id: "patient.welcome.book_nav",
    target: "shell.sidebar.book-appointment",
    title: "Book New Appointment",
    body: "This opens the booking wizard: intake, Medicare path, consents, and review. You can save progress and return later. Tap Next to open it.",
    side: "right",
    align: "start",
    waitForRoute: "/patient/account",
    pushPathOnNext: "/patient/book-appointment",
  },
  {
    id: "patient.welcome.book_wizard",
    target: "patient.page.book-appointment",
    title: "Booking wizard",
    body: "Follow the stepper at the top, save as you go, and use Back/Next inside the card. When you submit, confirmations flow to Appointments and notifications. Next returns you to the dashboard for a quick look at the top bar.",
    side: "left",
    align: "start",
    waitForRoute: "/patient/book-appointment",
    pushPathOnNext: "/patient/dashboard",
  },
  {
    id: "patient.welcome.header",
    target: "shell.header",
    title: "Top bar everywhere",
    body: "Logo (on small screens), search when visible, notifications, profile, and the tour “?” help button stay in the header on every patient page.",
    side: "bottom",
    align: "center",
    waitForRoute: "/patient/dashboard",
  },
  {
    id: "patient.welcome.notifications",
    target: "shell.header.notifications",
    title: "Notifications",
    body: "The bell lists booking updates, session reminders, and messages. Open it anytime; mark items read when you’re caught up.",
    side: "bottom",
    align: "end",
    waitForRoute: "/patient/dashboard",
  },
  {
    id: PATIENT_WELCOME_LAST_STEP_ID,
    target: "shell.header.profile",
    title: "Profile & initials",
    body: "Your initials link to account settings and onboarding. The ? beside the bell replays this tour or hides tutorials for this browser.",
    side: "bottom",
    align: "end",
    waitForRoute: "/patient/dashboard",
  },
]
